/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pa_23130628_proyecto_01;

import java.text.DecimalFormat;
import java.util.Random;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fer Landa Santi
 */
public class PA_23130628_Frame_01_TablaVehiculo extends javax.swing.JFrame {

    /**
     * Creates new form PA_23130628_Frame_01_TablaVehiculo
     */
    public void borrar(){
        for(int r = 0; r < jTableVehiculos.getRowCount(); r++)
            for(int c=0; c < jTableVehiculos.getColumnCount(); c++)
                jTableVehiculos.setValueAt(null, r, c);
        
for(int c=1; c < jTablePromedios.getColumnCount(); c++)
            jTablePromedios.setValueAt(null, 0, c);
        
        jLabMayor.setText("");
        jLabMenor.setText("");

    }

   private DecimalFormat formato = new DecimalFormat("#,###,##0.00");
    public PA_23130628_Frame_01_TablaVehiculo() {
        initComponents();
        
        jTableVehiculos.setShowGrid(true);
        jTablePromedios.setShowVerticalLines(true);        
        jTablePromedios.setValueAt("PROMEDIOS/SUMA", 0, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVehiculos = new javax.swing.JTable();
        jButCalcular = new javax.swing.JButton();
        jButEjemplo = new javax.swing.JButton();
        jButBorrar = new javax.swing.JButton();
        jButOrdenar = new javax.swing.JButton();
        jButAlfabetico = new javax.swing.JButton();
        jButMayorMenor = new javax.swing.JButton();
        jButAleatorios = new javax.swing.JButton();
        jSpinCarros = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabMayor = new javax.swing.JLabel();
        jLabMenor = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePromedios = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableVehiculos.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jTableVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vehiculos", "Distancia (m)", "Velocidad Inicial", "Aceleracion (m/s^2)", "Tiempo (s)"
            }
        ));
        jScrollPane1.setViewportView(jTableVehiculos);
        if (jTableVehiculos.getColumnModel().getColumnCount() > 0) {
            jTableVehiculos.getColumnModel().getColumn(0).setPreferredWidth(100);
        }

        jButCalcular.setBackground(new java.awt.Color(153, 255, 153));
        jButCalcular.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jButCalcular.setText("Calcular");
        jButCalcular.setOpaque(true);
        jButCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCalcularActionPerformed(evt);
            }
        });

        jButEjemplo.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jButEjemplo.setText("Ejemplo");
        jButEjemplo.setOpaque(true);
        jButEjemplo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEjemploActionPerformed(evt);
            }
        });

        jButBorrar.setBackground(new java.awt.Color(51, 51, 51));
        jButBorrar.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jButBorrar.setForeground(new java.awt.Color(255, 255, 255));
        jButBorrar.setText("Borrar");
        jButBorrar.setOpaque(true);
        jButBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButBorrarActionPerformed(evt);
            }
        });

        jButOrdenar.setBackground(new java.awt.Color(153, 255, 204));
        jButOrdenar.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jButOrdenar.setText("Ordenar");
        jButOrdenar.setOpaque(true);
        jButOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButOrdenarActionPerformed(evt);
            }
        });

        jButAlfabetico.setBackground(new java.awt.Color(153, 255, 204));
        jButAlfabetico.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jButAlfabetico.setText("Alfabetico");
        jButAlfabetico.setOpaque(true);
        jButAlfabetico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAlfabeticoActionPerformed(evt);
            }
        });

        jButMayorMenor.setBackground(new java.awt.Color(255, 204, 153));
        jButMayorMenor.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jButMayorMenor.setText("Mayor/Menor");
        jButMayorMenor.setOpaque(true);
        jButMayorMenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButMayorMenorActionPerformed(evt);
            }
        });

        jButAleatorios.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jButAleatorios.setText("Aleatorios");
        jButAleatorios.setOpaque(true);
        jButAleatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAleatoriosActionPerformed(evt);
            }
        });

        jSpinCarros.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        jSpinCarros.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinCarrosStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel1.setText("Número De Vehiculos");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("Vehiculo Con Mayor Tiempo");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setText("Vehiculo Con Menor Tiempo");

        jLabMayor.setBackground(new java.awt.Color(204, 204, 255));
        jLabMayor.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabMayor.setOpaque(true);

        jLabMenor.setBackground(new java.awt.Color(255, 153, 153));
        jLabMenor.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabMenor.setOpaque(true);

        jLabel6.setBackground(new java.awt.Color(255, 255, 204));
        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel6.setText("Movimiento rectilíneo uniformemente acelerado. Calcular el tiempo");
        jLabel6.setOpaque(true);

        jTablePromedios.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jTablePromedios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Vehiculos", "Distancia (m) Suma", "Velocidad Inicial Prom.", "Aceleracion (m/s^2) Prom.", "Tiempo (s) Suma"
            }
        ));
        jTablePromedios.setRowHeight(60);
        jScrollPane2.setViewportView(jTablePromedios);
        if (jTablePromedios.getColumnModel().getColumnCount() > 0) {
            jTablePromedios.getColumnModel().getColumn(0).setPreferredWidth(100);
        }

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pa_23130628_proyecto_01/AsignacionP1.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pa_23130628_proyecto_01/EjemploP1.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButAlfabetico, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButMayorMenor)
                                            .addComponent(jButOrdenar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jButBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jSpinCarros, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(118, 118, 118)
                                .addComponent(jButEjemplo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(jButAleatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButEjemplo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButAleatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jSpinCarros, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jButCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButOrdenar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButAlfabetico, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButMayorMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel5)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSpinCarrosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinCarrosStateChanged
        // TODO add your handling code here:
        
       int renglones = (int)jSpinCarros.getValue();
        DefaultTableModel modelo = (DefaultTableModel)jTableVehiculos.getModel();
        
        modelo.setRowCount(renglones);
    }//GEN-LAST:event_jSpinCarrosStateChanged

    private void jButAleatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAleatoriosActionPerformed
        // TODO add your handling code here:
        
        Random azar = new Random();
        String [] carros = 
        {"Abarth","Alfa Romeo", "Aston Martin", "Audi","Bentley","BMW","Cadillac","Caterham", "Chevrolet", "Citroen","Dacia","Ferrari","Fiat","Ford","Honda",
                "Infiniti","Isuzu","Iveco","Jaguar","Jeep","Kia	KTM","Lada","Lamborghini","Lancia","Land Rover","Lexus","Lotus","Maserati","Mazda","Mercedes-Benz",
                "Mini",	"Mitsubishi","Morgan","Nissan","Opel","Peugeot","Piaggio","Porsche","Renault","Rolls-Royce","Seat","Skoda","Smart","SsangYong",
                "Subaru","Suzuki","Tata","Tesla","Toyota", "Volkswagen ","Volvo"};
            // "BMW","Mercedes-Benz","Audi","Lexus","Renault","Ford","Opel","Seat", "Subaru","Suzuki", "Tata","Tesla", "Toyota","VolkswagenVolvo"};
            borrar();

        for(int r=0; r < jTableVehiculos.getRowCount();r++)
        {
            jTableVehiculos.setValueAt(carros[azar.nextInt(carros.length)], r, 0); // Vehiculos
            jTableVehiculos.setValueAt(azar.nextInt(10000, 500000), r, 1); // Distancia
            jTableVehiculos.setValueAt(azar.nextInt(20, 100), r, 2); // Velocidad Inicial
            jTableVehiculos.setValueAt(azar.nextInt(10, 50), r, 3); // Aceleracion
        }
    }//GEN-LAST:event_jButAleatoriosActionPerformed

    private void jButCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCalcularActionPerformed
        // TODO add your handling code here:
        double sumaTiempo = 0;
        double sumaDistancia = 0;
        double sumaVelocidadI = 0;
        double sumaAceleracion = 0;
        double veloProm = 0;
        double acelProm = 0;                
        for(int r=0; r < jTableVehiculos.getRowCount();r++)
        {
            Vehiculo car = new Vehiculo();
            car.setVehiculo(jTableVehiculos.getValueAt(r, 0) + "");
            car.setDistancia(Double.parseDouble(jTableVehiculos.getValueAt(r, 1) + ""));
            car.setVelocidadI(Double.parseDouble(jTableVehiculos.getValueAt(r, 2) + ""));
            car.setAceleracion(Double.parseDouble(jTableVehiculos.getValueAt(r, 3) + ""));            
            jTableVehiculos.setValueAt(formato.format(car.calcTiempo()), r, 4);
            
            
            sumaDistancia += car.getDistancia();
            sumaVelocidadI += car.getVelocidadI();
            sumaAceleracion += car.getAceleracion();
            sumaTiempo += car.calcTiempo();
            
            veloProm = sumaVelocidadI / jTableVehiculos.getRowCount();
            acelProm = sumaAceleracion / jTableVehiculos.getRowCount();
        }
        jTablePromedios.setValueAt(formato.format(sumaDistancia), 0, 1);
        jTablePromedios.setValueAt(formato.format(veloProm), 0, 2);
        jTablePromedios.setValueAt(formato.format(acelProm), 0, 3);
        jTablePromedios.setValueAt(formato.format(sumaTiempo), 0, 4);
        

    }//GEN-LAST:event_jButCalcularActionPerformed

    private void jButOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButOrdenarActionPerformed
        // TODO add your handling code here:

        Vehiculo[] lista = new Vehiculo[jTableVehiculos.getRowCount()];
        
        for(int r = 0; r < jTableVehiculos.getRowCount(); r++)
        {
            Vehiculo carr = new Vehiculo(); // crea un objeto nuevo en cada iteracion
            
            carr.setVehiculo(jTableVehiculos.getValueAt(r, 0) + "");
            carr.setDistancia(Double.parseDouble(jTableVehiculos.getValueAt(r, 1) + ""));
            carr.setVelocidadI(Double.parseDouble(jTableVehiculos.getValueAt(r, 2) + ""));
            carr.setAceleracion(Double.parseDouble(jTableVehiculos.getValueAt(r, 3) + ""));            
            jTableVehiculos.setValueAt(formato.format(carr.calcTiempo()), r, 4);
            
            // asignamos el objeto en la posicion r del arreglo
            lista [r] = carr;
        }
      
     // Usaremos el metodo de la burbuja
     // Primero agrego el ordenamiento alfabetico y luego el de tiempo para que los acomode por letra en caso de ser el mismo valor numerico
     for(int i=0; i < lista.length - 1; i++)
            for(int j= i+1; j < lista.length; j++)
                if(lista[i].getVehiculo().compareTo(lista[j].getVehiculo()) > 0){ // < = descendente   > = ascendente
                    Vehiculo veh = lista[i];
                    lista[i] = lista[j];
                    lista[j] = veh;
                }
     
     
        for(int i=0; i < lista.length - 1; i++)
            for(int j= i+1; j < lista.length; j++)
                if(lista[i].calcTiempo()< lista[j].calcTiempo()){ // < = descendente   > = ascendente
                    Vehiculo veh = lista[i];
                    lista[i] = lista[j];
                    lista[j] = veh;
                }
        
        //regresamos lo datos ya ordenados del jTable
        
        for(int r = 0; r < jTableVehiculos.getRowCount(); r++)
        {
            jTableVehiculos.setValueAt(lista[r].getVehiculo(), r, 0);
            jTableVehiculos.setValueAt(lista[r].getDistancia(), r, 1);
            jTableVehiculos.setValueAt(lista[r].getVelocidadI(), r, 2);
            jTableVehiculos.setValueAt(lista[r].getAceleracion(), r, 3);
            jTableVehiculos.setValueAt(formato.format(lista[r].calcTiempo()), r, 4);
        }
        


        
    }//GEN-LAST:event_jButOrdenarActionPerformed

    private void jButAlfabeticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAlfabeticoActionPerformed
        // TODO add your handling code here:
        
        
        Vehiculo[] lista = new Vehiculo[jTableVehiculos.getRowCount()];
        
        for(int r = 0; r < jTableVehiculos.getRowCount(); r++)
        {
            Vehiculo carr = new Vehiculo(); // crea un objeto nuevo en cada iteracion
            
            carr.setVehiculo(jTableVehiculos.getValueAt(r, 0) + "");
            carr.setDistancia(Double.parseDouble(jTableVehiculos.getValueAt(r, 1) + ""));
            carr.setVelocidadI(Double.parseDouble(jTableVehiculos.getValueAt(r, 2) + ""));
            carr.setAceleracion(Double.parseDouble(jTableVehiculos.getValueAt(r, 3) + ""));            
            jTableVehiculos.setValueAt(formato.format(carr.calcTiempo()), r, 4);
            
            // asignamos el objeto en la posicion r del arreglo
            lista [r] = carr;
        }
      
     // Usaremos el metodo de la burbuja
        for(int i=0; i < lista.length - 1; i++)
            for(int j= i+1; j < lista.length; j++)
                if(lista[i].getVehiculo().compareTo(lista[j].getVehiculo()) > 0){ // < = descendente   > = ascendente
                    Vehiculo veh = lista[i];
                    lista[i] = lista[j];
                    lista[j] = veh;
                }
        
        //regresamos lo datos ya ordenados del jTable
        
        for(int r = 0; r < jTableVehiculos.getRowCount(); r++)
        {
            jTableVehiculos.setValueAt(lista[r].getVehiculo(), r, 0);
            jTableVehiculos.setValueAt(lista[r].getDistancia(), r, 1);
            jTableVehiculos.setValueAt(lista[r].getVelocidadI(), r, 2);
            jTableVehiculos.setValueAt(lista[r].getAceleracion(), r, 3);
            jTableVehiculos.setValueAt(formato.format(lista[r].calcTiempo()), r, 4);
        }
    }//GEN-LAST:event_jButAlfabeticoActionPerformed

    private void jButMayorMenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButMayorMenorActionPerformed
        // TODO add your handling code here:
        Vehiculo mayor = new Vehiculo();
        Vehiculo menor = new Vehiculo();
        for(int r = 0; r < jTableVehiculos.getRowCount(); r++)
        {
            Vehiculo carr = new Vehiculo(); 
            
            carr.setVehiculo(jTableVehiculos.getValueAt(r, 0) + "");
            carr.setDistancia(Double.parseDouble(jTableVehiculos.getValueAt(r, 1) + ""));
            carr.setVelocidadI(Double.parseDouble(jTableVehiculos.getValueAt(r, 2) + ""));
            carr.setAceleracion(Double.parseDouble(jTableVehiculos.getValueAt(r, 3) + ""));            
            jTableVehiculos.setValueAt(formato.format(carr.calcTiempo()), r, 4);
            
            if(r==0){
                mayor = carr;
                menor = carr;
            }
            
            if(carr.calcTiempo() > mayor.calcTiempo())
                mayor = carr;
            if(carr.calcTiempo() < menor.calcTiempo())
                menor = carr;
            
        }
        
        jLabMayor.setText(mayor.getVehiculo());
        jLabMenor.setText(menor.getVehiculo());
    }//GEN-LAST:event_jButMayorMenorActionPerformed

    private void jButBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButBorrarActionPerformed
        // TODO add your handling code here:
        borrar();
//        for(int r = 0; r < jTableVehiculos.getRowCount(); r++)
//            for(int c=0; c < jTableVehiculos.getColumnCount(); c++)
//                jTableVehiculos.setValueAt(null, r, c);
//        
//        for(int c=4; c < jTableVehiculos.getColumnCount(); c++)
//            jTableVehiculos.setValueAt(null, 0, c);
//        
//        jLabPromedio.setText("");
//        jLabMayor.setText("");
//        jLabMenor.setText("");
    }//GEN-LAST:event_jButBorrarActionPerformed

    private void jButEjemploActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEjemploActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel)jTableVehiculos.getModel();
        jSpinCarros.setValue(5);
        // modelo.setRowCount(5);
        borrar();
        jTableVehiculos.setValueAt("Mustang", 0, 0);
        jTableVehiculos.setValueAt("Cheyenne", 1, 0);
        jTableVehiculos.setValueAt("BMW", 2, 0);
        jTableVehiculos.setValueAt("Vocho", 3, 0);
        jTableVehiculos.setValueAt("Ferrari", 4, 0);
        
         jTableVehiculos.setValueAt(113400, 0, 1);
        jTableVehiculos.setValueAt(31500, 1, 1);
        jTableVehiculos.setValueAt(113400, 2, 1);
        jTableVehiculos.setValueAt(45825, 3, 1);
        jTableVehiculos.setValueAt(113400, 4, 1);
        
        jTableVehiculos.setValueAt(45, 0, 2);
        jTableVehiculos.setValueAt(25, 1, 2);
        jTableVehiculos.setValueAt(45, 2, 2);
        jTableVehiculos.setValueAt(55, 3, 2);
        jTableVehiculos.setValueAt(45, 4, 2);
        
        jTableVehiculos.setValueAt(15, 0, 3);
        jTableVehiculos.setValueAt(30, 1, 3);
        jTableVehiculos.setValueAt(15, 2, 3);
        jTableVehiculos.setValueAt(20, 3, 3);
        jTableVehiculos.setValueAt(15, 4, 3);
        
        
    }//GEN-LAST:event_jButEjemploActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PA_23130628_Frame_01_TablaVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PA_23130628_Frame_01_TablaVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PA_23130628_Frame_01_TablaVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PA_23130628_Frame_01_TablaVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PA_23130628_Frame_01_TablaVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButAleatorios;
    private javax.swing.JButton jButAlfabetico;
    private javax.swing.JButton jButBorrar;
    private javax.swing.JButton jButCalcular;
    private javax.swing.JButton jButEjemplo;
    private javax.swing.JButton jButMayorMenor;
    private javax.swing.JButton jButOrdenar;
    private javax.swing.JLabel jLabMayor;
    private javax.swing.JLabel jLabMenor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinCarros;
    private javax.swing.JTable jTablePromedios;
    private javax.swing.JTable jTableVehiculos;
    // End of variables declaration//GEN-END:variables
}
